kind: Operation
key: installation
title: Installation

prerequisites:
  - move-to-own-pvc.current-pvc-is-default
  - move-to-own-pvc.backups-enabled
  - move-to-own-pvc.current-db-exists

stages:

#  - 'nectar.auditing.strategy'

  - key: application
    title: Policies
    info: "Define global policies to limit the application's access to
    resources, as well well as its network visibility across the cluster."
    steps:
      - step.global.quotas.requests
      - step.global.quotas.limits

  - key: storage
    kind: Stage
    title: Primary Storage
    info: "Nectar Hub needs a database in order to work. The following
    steps will let you choose how storage is allocated and
     how the database is secured."
    steps:
      - installation.storage_strategy
      - installation.decide_pvc_strategy
      - installation.locate_external_pvc
      - installation.locate_external_db
      - installation.set_db_secrets

  - key: hub-settings
    kind: Stage
    title: Hub Settings
    info: "Configure the application at the infrastructure level.
      This installer only exposes a subset of all possible fields. You can configure
      the application further after the installer completes."
    steps:
      - installation.encryption
      - installation.availability

  - key: backups
    kind: Stage
    title: Backups
    info: "Backups are an important part of hosting stateful
      applications. Nectar provides pre-build backup solutions
      for compatible the various storage strategies."
    steps:
      - installation.backups_strategy

  - key: networking
    kind: Stage
    title: Networking
    info: "Nectar Hub is accessible in a number of ways. The following
    steps expose the basic parameters for Hub's networking behavior."
    steps:
      - installation.network_strategy
      - installation.networking_host