FROM ruby:2.6.3-alpine3.10
WORKDIR /app
RUN apk --update add build-base libxslt-dev libxml2-dev
ADD Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install
ADD . /app
RUN rm values.yaml
RUN mv values-2.0.0.yaml values.yaml
ENTRYPOINT ["bundle", "exec", "ruby", "/app/main.rb"]